apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app
        ports:
          - containerPort: 8080
            protocol: TCP
        image: 573546863626.dkr.ecr.us-east-1.amazonaws.com/myapp:v1.0
        env:
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "dbpwd"
        - name: DBHOST
          value: "mysql.abhishek.svc.cluster.local"
        - name: DBUSER
          value: "root"